// web/src/components/config/advanced.tsx
import styled from "styled-components";
import { Stack } from "../base/stack";
import { useAtom } from "jotai";
import {
  considerCharacteristicsAtom,
  continuousOptimisationAtom,
  initialTemperatureAtom,
  numberOfIterationsAtom,
} from "@/state/state";
import { InputDecimal } from "../base/input";
import { Tooltip } from "../base/tooltip";
import { Language, languageAtom } from "@/state/languageState";

const AdvancedConfigStack = styled(Stack)`
  flex-wrap: wrap;
  gap: 16px;
`;

const TooltipBox = styled.div`
  background-color: white;
  border: 1px solid black;
  border-radius: 8px;
  padding: 4px;
`;

function LanguageInput() {
  const [language, setLanguage] = useAtom(languageAtom);

  return (
    <label>
      Language:{" "}
      <select
        value={language}
        onChange={(evt) => setLanguage(evt.target.value as Language)}
      >
        <option value="en">English</option>
        <option value="fr">Français</option>
      </select>
    </label>
  );
}

export function AdvancedConfig() {
  const [iterations, setIterations] = useAtom(numberOfIterationsAtom);
  const [initialTemperature, setInitialTemperature] = useAtom(
    initialTemperatureAtom
  );
  const [continuous, setContinuous] = useAtom(continuousOptimisationAtom);
  const [characteristics, setCharacteristics] = useAtom(
    considerCharacteristicsAtom
  );

  return (
    <AdvancedConfigStack $dir="h">
      <label>
        Number of iterations:{" "}
        <InputDecimal
          value={iterations}
          onChange={(evt) => setIterations(evt)}
        />
      </label>
      <label>
        Initial temperature:{" "}
        <InputDecimal
          value={initialTemperature}
          onChange={(evt) => setInitialTemperature(evt)}
        />
      </label>
      <label>
        Continuous optimisation:{" "}
        <input
          type="checkbox"
          checked={continuous}
          onChange={(evt) => setContinuous(evt.target.checked)}
        />
      </label>
      <label>
        <Tooltip
          tooltip={
            <TooltipBox>
              You may want to consider increasing the number of iterations to
              make this more accurate
            </TooltipBox>
          }
        >
          Consider characteristics points:{" "}
          <input
            type="checkbox"
            checked={characteristics}
            onChange={(evt) => setCharacteristics(evt.target.checked)}
          />
        </Tooltip>
      </label>
      <LanguageInput />
    </AdvancedConfigStack>
  );
}

// web/src/lib/optimiser/advanced.svelte
<script lang="ts">
  import Section from "$lib/component/section.svelte";
  import { language } from "$lib/state/lang.svelte";
  import { dofusState, optimiserConfig } from "./state.svelte";
</script>

<Section title="Advanced">
  <div class="wrapper">
    <label>
      Number of iterations
      <input type="number" bind:value={optimiserConfig.numberOfIterations} />
    </label>
    <label>
      Initial temperature
      <input
        type="number"
        bind:value={optimiserConfig.initialTemperature}
        step="any"
      />
    </label>
    <label>
      Continuous optimisation
      <input type="checkbox" bind:checked={optimiserConfig.continuous} />
    </label>
    <label>
      Consider characteristics points
      <input
        type="checkbox"
        bind:checked={dofusState.considerCharacteristicPoints}
      />
    </label>
    <label>
      Language
      <select bind:value={language.lang}>
        <option value="en">English</option>
        <option value="fr">Français</option>
      </select>
    </label>
  </div>
</Section>

<style>
  .wrapper {
    display: flex;
    gap: 16px;
  }

  label {
    display: flex;
    align-items: center;
    gap: 4px;
  }
</style>
