// web/src/lib/optimiser/exos.svelte
<script lang="ts">
  import Section from "$lib/component/section.svelte";
  import { getUrlForStatIcon, type StatName } from "$lib/dofus/stat-names";
  import { dofusState } from "./state.svelte";

  type ExoTypes = "apExo" | "mpExo" | "rangeExo" | "multiElement";
</script>

{#snippet Exo(name: string, id: ExoTypes, icon?: StatName)}
  <label class="exo">
    {#if icon}
      <img src={getUrlForStatIcon(icon)} alt="" />
    {/if}
    <span>{name}</span>
    <input type="checkbox" bind:checked={dofusState[id]} />
  </label>
{/snippet}

<Section title="Exos" open>
  <div class="wrapper">
    {@render Exo("AP Exo", "apExo", "AP")}
    {@render Exo("MP Exo", "mpExo", "MP")}
    {@render Exo("Range Exo", "rangeExo", "Range")}
    {@render Exo("Multi", "multiElement")}
  </div>
</Section>

<style>
  img {
    width: 15px;
    height: 15px;
  }

  .exo {
    display: flex;
    align-items: center;
    gap: 2px;
  }

  .wrapper {
    display: flex;
    gap: 8px;
  }
</style>

// web/src/components/exos.tsx
import { getStatIconUrl, StatName } from "@/services/dofus/stats";
import { exosState } from "@/state/state";
import { useAtom } from "jotai";
import styled from "styled-components";

interface ExoProps {
  name: string;
  icon?: StatName;
  id: keyof typeof exosState.init;
}

const Icon = styled.img`
  width: 15px;
  height: 15px;
`;

const ExoWrapper = styled.label`
  display: flex;
  align-items: center;
  gap: 2px;
`;

function Exo({ name, icon, id }: ExoProps) {
  const [exos, setExos] = useAtom(exosState);
  const value = exos[id];
  const iconUrl = icon ? getStatIconUrl(icon) : undefined;

  return (
    <ExoWrapper>
      {icon && <Icon src={iconUrl} alt="" aria-hidden="true" />}
      <span>{name}</span>
      <input
        type="checkbox"
        checked={value}
        onChange={(evt) => setExos({ ...exos, [id]: evt.target.checked })}
      />
    </ExoWrapper>
  );
}

const ExosWrapper = styled.div`
  display: flex;
  gap: 8px;
`;

export function ExosInputs() {
  return (
    <ExosWrapper>
      <Exo name="AP Exo" id="apExo" icon="AP" />
      <Exo name="MP Exo" id="mpExo" icon="MP" />
      <Exo name="Range Exo" id="rangeExo" icon="Range" />
      <Exo name="Multi" id="multiElement" />
    </ExosWrapper>
  );
}
